djangocore/apps/base/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

from djangocore.configs import DEBUG

app_name = 'base'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

if DEBUG:
    urlpatterns += [
        url(r'^404/$', views.handler404),
        url(r'^500/$', views.handler500),
    ]

djangocore/apps/exemplo/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = 'exemplo'
urlpatterns = [

    url(r'exemplo/lista/$', views.ListView.as_view(), name='listaexemplo'),
    url(r'exemplo/adicionar/$', views.AdicionarView.as_view(), name='adicionaexemplo'),
    url(r'exemplo/editar/(?P<pk>[0-9]+)/$', views.EditarView.as_view(), name='editaexemplo'),

]

djangocore/apps/flavio/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = 'flavio'
urlpatterns = [

    url(r'flavio/lista/$', views.ListView.as_view(), name='listaflavio'),
    url(r'flavio/adicionar/$', views.AdicionarView.as_view(), name='adicionaflavio'),
    url(r'flavio/editar/(?P<pk>[0-9]+)/$', views.EditarView.as_view(), name='editaflavio'),

    # Pessoa #
    url(r'flavio/lista_pessoa/$', views.ListPessoaView.as_view(), name='lista_pessoa'),
    url(r'flavio/adicionar_pessoa/$', views.AdicionarPessoaView.as_view(), name='adiciona_pessoa'),
    url(r'flavio/editar_pessoa/(?P<pk>[0-9]+)/$', views.EditarPessoaView.as_view(), name='edita_pessoa'),

]

djangocore/apps/login/urls.py
from django.conf.urls import url
from . import views

app_name = 'login'
urlpatterns = [
    # login/
    url(r'^$', views.UserFormView.as_view(), name='loginview'),

    # login/registrar/
    url(r'registrar/$', views.UserRegistrationFormView.as_view(),
        name='registrarview'),

    # login/esqueceu/:
    url(r'^esqueceu/$', views.ForgotPasswordView.as_view(), name='esqueceuview'),

    # login/trocarsenha/:
    url(r'^trocarsenha/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)$',
        views.PasswordResetConfirmView.as_view(), name='trocarsenhaview'),

    # logout
    url(r'^logout/$', views.UserLogoutView.as_view(), name='logoutview'),

    # login/perfil/
    url(r'^perfil/$', views.MeuPerfilView.as_view(), name='perfilview'),

    # login/editarperfil/
    url(r'^editarperfil/$', views.EditarPerfilView.as_view(), name='editarperfilview'),

    # login/usuarios/
    url(r'^usuarios/$', views.UsuariosListView.as_view(), name='usuariosview'),

    # login/usuarios/(id_usuario)
    url(r'usuarios/(?P<pk>[0-9]+)/$',
        views.UsuarioDetailView.as_view(), name='usuariodetailview'),

    # deletar usuario
    url(r'deletaruser/(?P<pk>[0-9]+)/$',
        views.DeletarUsuarioView.as_view(), name='deletarusuarioview'),

    # permissoes usuario
    url(r'permissoesusuario/(?P<pk>[0-9]+)/$',
        views.EditarPermissoesUsuarioView.as_view(), name='permissoesusuarioview'),


]

djangocore/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from .configs.settings import DEBUG, MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('djangocore.apps.base.urls')),
    url(r'^login/', include('djangocore.apps.login.urls')),
    url(r'^importador/', include('djangocore.apps.importador.urls')),
    url(r'^importador/', include('djangocore.apps.exemplo.urls')),
    url(r'^flavio/', include('djangocore.apps.flavio.urls')),
    url(r'^viagem/', include('djangocore.apps.viagem.urls')),
    url(r'^viagem/', include('djangocore.apps.timesheet.urls')),
    url(r'^viagem/', include('djangocore.apps.leasing.urls')),


]

if DEBUG is True:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

djangocore/apps/exemplo/models/exemplo.py
from django.db import models


class ExemploModel(models.Model):
    nome = models.CharField(max_length=200)
    apelido = models.CharField(max_length=200)

djangocore/apps/base/views.py
# -*- coding: utf-8 -*-

from django.views.generic import TemplateView
from django.shortcuts import render
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import F



from datetime import datetime


class IndexView(TemplateView):
    template_name = 'base/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        data_atual = datetime.now().date()

        context['data_atual'] = data_atual.strftime('%d/%m/%Y')

        return context


def handler404(request):
    response = render(request, '404.html', {})
    response.status_code = 404
    return response


def handler500(request):
    response = render(request, '500.html', {})
    response.status_code = 500
    return response

djangocore/apps/exemplo/views/exemplo.py
# -*- coding: utf-8 -*-

from django.urls import reverse_lazy

from djangocore.apps.base.custom_views import CustomCreateView, CustomListView, CustomUpdateView


from djangocore.apps.exemplo.forms.FormExemplo import ExemploForm
from djangocore.apps.exemplo.models.exemplo import ExemploModel



class ListView(CustomListView):
    template_name = 'exemplo/exemplo_operacao/list.html'
    model = ExemploModel
    context_object_name = 'all_natops'
    success_url = reverse_lazy('exemplo:listaexemplo')
    permission_codename = 'view_naturezaoperacao'

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        context['title_complete'] = 'Exemplo'
        context['add_url'] = reverse_lazy('exemplo:adicionaexemplo')
        return context

class AdicionarView(CustomCreateView):
    #form_class = NaturezaOperacaoForm
    form_class = ExemploForm
    template_name = "exemplo/exemplo_operacao/add.html"
    success_url = reverse_lazy('exemplo:listaexemplo')
    success_message = "Adicionar Exemplo <b>%(cfop)s </b>adicionado com sucesso."
    permission_codename = 'add_naturezaoperacao'

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, cfop=self.object.cfop)

    def get_context_data(self, **kwargs):
        context = super(AdicionarView, self).get_context_data(**kwargs)
        context['title_complete'] = 'ADICIONAR EXEMPLO'
        context['return_url'] = reverse_lazy('exemplo:listaexemplo')
        return context





class EditarView(CustomUpdateView):
    print('Ok')
    form_class = ExemploForm
    model = ExemploModel
   # template_name = "fiscal/natureza_operacao/natureza_operacao_edit.html"
    template_name = "exemplo/exemplo_operacao/edit.html"
    success_url = reverse_lazy('exemplo:listaexemplo')
    success_message = "Natureza da operação <b>%(cfop)s </b>editada com sucesso."
    permission_codename = 'change_naturezaoperacao'

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, cfop=self.object.cfop)

    def get_context_data(self, **kwargs):
        context = super(EditarView,
                        self).get_context_data(**kwargs)
        context['return_url'] = reverse_lazy(
            'exemplo:listaexemplo')
        return context

djangocore/apps/flavio/views/View.py
# -*- coding: utf-8 -*-

from django.urls import reverse_lazy

from djangocore.apps.base.custom_views import CustomCreateView, CustomListView, CustomUpdateView


from djangocore.apps.flavio.forms.Form import *
from djangocore.apps.flavio.models.Model import *

### Carro ###

class ListView(CustomListView):
    template_name = 'flavio/list.html' #'exemplo/exemplo_operacao/list.html'
    model = CarroModel
    context_object_name = 'all_natops'
    success_url = reverse_lazy('flavio:listaflavio')
    permission_codename = 'view_naturezaoperacao'

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        context['title_complete'] = 'Carro'
        context['add_url'] = reverse_lazy('flavio:adicionaflavio')
        return context
#
class AdicionarView(CustomCreateView):
    form_class = CarroForm
    template_name = 'flavio/add.html' #"exemplo/exemplo_operacao/add.html"
    success_url = reverse_lazy('flavio:listaflavio')
    success_message = "Adicionar Exemplo <b>%(cfop)s </b>adicionado com sucesso."
    permission_codename = 'add_naturezaoperacao'

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, cfop=self.object.cfop)

    def get_context_data(self, **kwargs):
        context = super(AdicionarView, self).get_context_data(**kwargs)
        context['title_complete'] = 'ADICIONAR EXEMPLO'
        context['return_url'] = reverse_lazy('flavio:listaflavio')
        return context





class EditarView(CustomUpdateView):
    form_class = CarroForm
    model = CarroModel
   # template_name = "fiscal/natureza_operacao/natureza_operacao_edit.html"
    template_name = 'flavio/edit.html' #"exemplo/exemplo_operacao/edit.html"
    success_url = reverse_lazy('flavio:listaflavio')
    success_message = "Natureza da operação <b>%(cfop)s </b>editada com sucesso."
    permission_codename = 'change_naturezaoperacao'

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, cfop=self.object.cfop)

    def get_context_data(self, **kwargs):
        context = super(EditarView,
                        self).get_context_data(**kwargs)
        context['return_url'] = reverse_lazy(
            'flavio:listaflavio')
        return context




### Pessoa ###

class ListPessoaView(CustomListView):
    template_name = 'flavio/list_pessoa.html'
    model = PessoaModel
    context_object_name = 'all_natops'
    success_url = reverse_lazy('flavio:lista_pessoa')
    permission_codename = 'view_naturezaoperacao'

    def get_context_data(self, **kwargs):
        context = super(ListPessoaView, self).get_context_data(**kwargs)
        context['title_complete'] = 'Pessoa'
        context['add_url'] = reverse_lazy('flavio:adiciona_pessoa')
        return context
#
class AdicionarPessoaView(CustomCreateView):
    form_class = PessoaForm
    template_name = 'flavio/add.html' #"exemplo/exemplo_operacao/add.html"
    success_url = reverse_lazy('flavio:lista_pessoa')
    success_message = "Adicionar Exemplo <b>%(cfop)s </b>adicionado com sucesso."
    permission_codename = 'add_naturezaoperacao'

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, cfop=self.object.cfop)

    def get_context_data(self, **kwargs):
        context = super(AdicionarPessoaView, self).get_context_data(**kwargs)
        context['title_complete'] = 'ADICIONAR EXEMPLO'
        context['return_url'] = reverse_lazy('flavio:lista_pessoa')
        return context





class EditarPessoaView(CustomUpdateView):
    form_class = PessoaForm
    model = PessoaModel
    template_name = 'flavio/edit.html' #"exemplo/exemplo_operacao/edit.html"
    success_url = reverse_lazy('flavio:lista_pessoa')
    success_message = "Natureza da operação <b>%(cfop)s </b>editada com sucesso."
    permission_codename = 'change_naturezaoperacao'

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, cfop=self.object.cfop)

    def get_context_data(self, **kwargs):
        context = super(EditarPessoaView,
                        self).get_context_data(**kwargs)
        context['return_url'] = reverse_lazy(
            'flavio:lista_pessoa')
        return context

djangocore/apps/importador/views/Views.py
from django.urls import reverse_lazy
from siconfipy import get_fiscal, get_budget, br_cods, get_annual_acc
from djangocore.apps.base.custom_views import CustomCreateView, CustomListView, CustomUpdateView

from datetime import timedelta, date, datetime
from djangocore.apps.importador.forms import *
from djangocore.apps.importador.models import *






class ListRGFView(CustomListView):
    template_name = 'RGF/list.html'
    model = RGFModel
    context_object_name = 'all_natops'
    success_url = reverse_lazy('importador:eac')
    permission_codename = 'rgf'

    def get_context_data(self, **kwargs):
        context = super(ListRGFView, self).get_context_data(**kwargs)
        context['title_complete'] = 'RGF'
        return context



class ListEACView(CustomListView):
    template_name = 'EAC/list.html'
    model = EACModel
    context_object_name = 'all_natops'
    success_url = reverse_lazy('importador:eac')
    permission_codename = 'eac'

    def get_context_data(self, **kwargs):
        context = super(ListEACView, self).get_context_data(**kwargs)
        context['title_complete'] = 'EAC'
        return context


class ListRREOView(CustomListView):
    template_name = 'RREO/list.html'
    model = RREOModel
    context_object_name = 'all_natops'
    success_url = reverse_lazy('importador:rreo')
    permission_codename = 'rreo'

    def get_context_data(self, **kwargs):
        context = super(ListRREOView, self).get_context_data(**kwargs)
        context['title_complete'] = 'RREO'
        return context




class ListImportacoesView(CustomListView):
    template_name = 'importador/list.html'
    model = ImportacaoModel
    context_object_name = 'all_natops'
    success_url = reverse_lazy('importador:listimportacoes')
    permission_codename = 'importar_dados'

    def get_context_data(self, **kwargs):
        if self.check_user_permissions(self.request):
            context = super(ListImportacoesView, self).get_context_data(**kwargs)
            context['title_complete'] = 'Importações'
            context['add_url'] = reverse_lazy('importador:adicionaimportacao')
            return context




class AddImportacoesView(CustomListView):
    form_class = ImportacaoForm
    template_name = "importador/add.html"
    success_url = reverse_lazy('importador:listimportacoes')
    success_message = "Importar Dados"
    permission_codename = 'importar_dados'


    def import_rreo(self, ano, bimestre, estado):

        dados = get_budget(year=ano, period=bimestre, cod=estado)
        for index, row in dados.iterrows():
            relatorio = RREOModel.objects.create()
            relatorio.exercicio = row['exercicio']
            relatorio.demonstrativo = row['demonstrativo']
            relatorio.periodo = row['periodo']
            relatorio.periodicidade = row['periodicidade']
            relatorio.instituicao = row['instituicao']
            relatorio.cod_ibge = row['cod_ibge']
            relatorio.uf = row['uf']
            relatorio.anexo = row['populacao']
            relatorio.anexo = row['anexo']
            relatorio.esfera = row['esfera']
            relatorio.rotulo = row['rotulo']
            relatorio.coluna = row['coluna']
            relatorio.cod_conta = row['cod_conta']
            relatorio.conta = row['conta']
            relatorio.valor = row['valor']
            relatorio.importacao = self.object
            relatorio.save()

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            self.object = form.save()

        tipo_relatorio = request.POST['tipo_relatorio']
        ano = request.POST['ano']
        estado = request.POST['estado']
        bimestre = request.POST['bimestre']

#16:51


        if tipo_relatorio == 'RREO':
            estados = {12, 27, 16, 13, 29, 23, 53, 32, 52, 21, 51, 50, 31, 15, 25, 41, 26, 22, 24, 43, 33, 11, 14, 42,
                       35, 28, 17}



            startDate = datetime.datetime.strptime('2015-01-01', '%Y-%m-%d')
            endDate = datetime.datetime.strptime(str(date.today()), '%Y-%m-%d')
            for x in range(startDate.year, endDate.year):
                for y in range(1, 7):
                    print(x, y)
                    for key in estados:
                        self.import_rreo(x, y, key)

            month = date.today().month
            if month > 2:
                for key in estados:
                    self.import_rreo(endDate.year, 1, key)
            if month > 4:
                for key in estados:
                    self.import_rreo(endDate.year, 2, key)
            if month > 6:
                for key in estados:
                    self.import_rreo(endDate.year, 3, key)
            if month > 8:
                for key in estados:
                    self.import_rreo(endDate.year, 4, key)
            if month > 10:
                for key in estados:
                    self.import_rreo(endDate.year, 5, key)
            if month >= 12:
                for key in estados:
                    self.import_rreo(endDate.year, 6, key)

        return super(AddImportacoesView, self).post(request, form, *args, **kwargs)

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, cfop=self.object.cfop)

    def get_context_data(self, **kwargs):
        context = super(AddImportacoesView, self).get_context_data(**kwargs)
        context['title_complete'] = 'Importar Dados'
        context['return_url'] = reverse_lazy('importador:listimportacoes')
        return context




class EditImportacoesView(CustomUpdateView):
    form_class = ImportacaoForm
    model = ImportacaoModel

    template_name = "importador/edit.html"
    success_url = reverse_lazy('importador:listimportacoes')
    success_message = "Importação realizada com sucesso."
    permission_codename = 'importar_dados'

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, cfop=self.object.cfop)

    def get_context_data(self, **kwargs):
        context = super(EditImportacoesView, self).get_context_data(**kwargs)
        context['return_url'] = reverse_lazy('importador:listimportacoes')
        return context

djangocore/templates/exemplo/exemplo_operacao/exemplo_operacao_add.html
{%extends 'base/base.html'%}

{%block title%}{{title_complete|title}}{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid">

    {% include 'base/title_header.html' %}

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="row">
        <div class="card">

          <!--Header-->
          <div class="header">

            <h2>
              <a href="{{return_url}}"><i class="material-icons">&#xE5C4;</i></a>{{title_complete}}
            </h2>
            <div><small>Campos marcados com <strong style="color:red;">*</strong> são obrigatórios.</small></div>

          </div>
          <!--# Header-->

          <form id="" role="form" action="" method="post">
            {% csrf_token %}
            <!-- Body-->
            <div class="body">
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">                

                {% for field in form %}
                <div class="col-sm-6">
                  <div class="form-group">
                    <div class="form-line">

                      <label>{{field.label}}</label>{% if field.field.required %}<strong style="color:red;"> *</strong>{% endif %}
                      {% if field.errors %}<label class="error">{% for error in field.errors %}{{error}}{% endfor %}</label>{% endif %}
                      {{field}}
                    </div>
                  </div>
                </div>
                {% endfor %}
                  
              </div>

              <button class="btn btn-success foot-btn" type="submit"><i class="material-icons">&#xE148;</i><span> SALVAR</span></button>
            </div>
            <!--#Body-->
          </form>

        </div>
      </div>
    </div>

  </div>
</section>


{%endblock%}

{% block js %}
    
  {% load static %}
  <!-- JQuery UI Css/Js -->
  <link href="{% static 'css/jquery-ui/jquery-ui.min.css' %}" rel="stylesheet">
  <script src="{% static 'js/jquery-ui.min.js' %}"></script>

  <script type="text/javascript">
    var cfop_path = '{% static 'tabelas/cfop/cfop_2015_002.csv' %}'
    $.Admin.autocompleteField.autocompleteCfop(cfop_path);
    
  </script>
  
{% endblock %}

djangocore/templates/exemplo/exemplo_operacao/exemplo_operacao_edit.html
{%extends 'base/base.html'%}


{%block title%} {{form.cfop.value}} {%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid">

    {% include 'base/title_header.html' %}

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="row">
        <div class="card">

          <!--Header-->
          <div class="header">

            <h2>
              <a href="{{return_url}}"><i class="material-icons">&#xE5C4;</i></a>{{form.cfop.value}}
            </h2>
            <div><small>Campos marcados com <strong style="color:red;">*</strong> são obrigatórios.</small></div>

          </div>
          <!--# Header-->

          <form role="form" action="" method="post">
            {% csrf_token %}
            <!-- Body-->
            <div class="body">
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
               
                {% for field in form %}
                <div class="col-sm-6">
                  <div class="form-group">
                    <div class="form-line">
                      <label>{{field.label}}</label>{% if field.field.required %}<strong style="color:red;"> *</strong>{% endif %}
                      {% if field.errors %}<label class="error">{% for error in field.errors %}{{error}}{% endfor %}</label>{% endif %}
                      {{field}}
                    </div>
                  </div>
                </div>
                {% endfor %}
                
              </div>
              <button class="btn btn-success foot-btn" type="submit"><i class="material-icons">&#xE148;</i><span> SALVAR</span></button>
            </div>
            <!--#Body-->
          </form>
          
        </div>
      </div>
    </div>

  </div>
</section>


{%endblock%}

{% block js %}
    
  {% load static %}
  <!-- JQuery UI Css/Js -->
  <link href="{% static 'css/jquery-ui/jquery-ui.min.css' %}" rel="stylesheet">
  <script src="{% static 'js/jquery-ui.min.js' %}"></script>

  <script type="text/javascript">
    var cfop_path = '{% static 'tabelas/cfop/cfop_2015_002.csv' %}'
    $.Admin.autocompleteField.autocompleteCfop(cfop_path);
    
  </script>
  
{% endblock %}

djangocore/templates/exemplo/exemplo_operacao/exemplo_operacao_list.html
{%extends 'base/base.html'%}

{%block title%}{{title_complete|title}}{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid lista">
  
    {% include 'base/title_header.html' %}
    
    {% include 'base/msg_sucesso.html' %}

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 lista-content">
      <div class="card">
        <form action="" method="post">
          {% csrf_token %}
          <div class="header">
            <h2>
              {{title_complete}}
            </h2>
              <div class="header-btn">
                <a href="{{add_url}}" class="btn btn-success"><i class="material-icons">&#xE148;</i><span> ADICIONAR</span></a>
                <button class="btn btn-red btn-remove"><i class="material-icons">&#xE872;</i></button>
              </div>
          </div>

          <div class="body">

           {% include 'base/search.html' %}

           <div class="table-responsive">
            <table id="lista-database" class="table table-bordered table-striped lista-table">
              <thead>
                <tr>
                  <th>Nome</th>
                  <th>Data de Publicação</th>
                  <th>Remover</th>
                </tr>
              </thead>

              <tbody>
               {% if all_natops%}
               {% for natop in all_natops %}

               <tr class="clickable-row"  data-href="{% url 'exemplo:editaexemplo' natop.id %}">
                <td>{{natop.nome}}</td>
                <td>{{natop.apelido}}</td>
                <td class="lista-remove">
                  <input type="checkbox" name="{{natop.id}}" id="remover-entrada-{{natop.id}}"/>
                  <label class="remove-entry-label" for="remover-entrada-{{natop.id}}"></label>
                </td>
              </tr>
              {% endfor %}
              {%else%}
              {%endif%}
            </tbody>
          </table>
        </div>

      </div>

    </form>

  </div>
</div>

</div>
</section>


{%endblock%}