djangocore/apps/base/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

from djangocore.configs import DEBUG

app_name = 'base'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

if DEBUG:
    urlpatterns += [
        url(r'^404/$', views.handler404),
        url(r'^500/$', views.handler500),
    ]

djangocore/apps/flavio/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = 'flavio'
urlpatterns = [

    url(r'flavio/lista/$', views.ListView.as_view(), name='listaflavio'),
    url(r'flavio/adicionar/$', views.AdicionarView.as_view(), name='adicionaflavio'),
    url(r'flavio/editar/(?P<pk>[0-9]+)/$', views.EditarView.as_view(), name='editaflavio'),

    # Pessoa #
    url(r'flavio/lista_pessoa/$', views.ListPessoaView.as_view(), name='lista_pessoa'),
    url(r'flavio/adicionar_pessoa/$', views.AdicionarPessoaView.as_view(), name='adiciona_pessoa'),
    url(r'flavio/editar_pessoa/(?P<pk>[0-9]+)/$', views.EditarPessoaView.as_view(), name='edita_pessoa'),

]

djangocore/apps/login/urls.py
from django.conf.urls import url
from . import views

app_name = 'login'
urlpatterns = [
    # login/
    url(r'^$', views.UserFormView.as_view(), name='loginview'),

    # login/registrar/
    url(r'registrar/$', views.UserRegistrationFormView.as_view(),
        name='registrarview'),

    # login/esqueceu/:
    url(r'^esqueceu/$', views.ForgotPasswordView.as_view(), name='esqueceuview'),

    # login/trocarsenha/:
    url(r'^trocarsenha/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)$',
        views.PasswordResetConfirmView.as_view(), name='trocarsenhaview'),

    # logout
    url(r'^logout/$', views.UserLogoutView.as_view(), name='logoutview'),

    # login/perfil/
    url(r'^perfil/$', views.MeuPerfilView.as_view(), name='perfilview'),

    # login/editarperfil/
    url(r'^editarperfil/$', views.EditarPerfilView.as_view(), name='editarperfilview'),

    # login/usuarios/
    url(r'^usuarios/$', views.UsuariosListView.as_view(), name='usuariosview'),

    # login/usuarios/(id_usuario)
    url(r'usuarios/(?P<pk>[0-9]+)/$',
        views.UsuarioDetailView.as_view(), name='usuariodetailview'),

    # deletar usuario
    url(r'deletaruser/(?P<pk>[0-9]+)/$',
        views.DeletarUsuarioView.as_view(), name='deletarusuarioview'),

    # permissoes usuario
    url(r'permissoesusuario/(?P<pk>[0-9]+)/$',
        views.EditarPermissoesUsuarioView.as_view(), name='permissoesusuarioview'),


]

djangocore/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from .configs.settings import DEBUG, MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('djangocore.apps.base.urls')),
    url(r'^login/', include('djangocore.apps.login.urls')),
    url(r'^importador/', include('djangocore.apps.importador.urls')),
    url(r'^importador/', include('djangocore.apps.exemplo.urls')),
    url(r'^flavio/', include('djangocore.apps.flavio.urls')),
    url(r'^viagem/', include('djangocore.apps.viagem.urls')),
    url(r'^viagem/', include('djangocore.apps.timesheet.urls')),
    url(r'^viagem/', include('djangocore.apps.leasing.urls')),


]

if DEBUG is True:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

djangocore/apps/exemplo/forms/FormExemplo.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import ugettext_lazy as _
import datetime
from djangocore.apps.exemplo.models import ExemploModel




class ExemploForm(forms.ModelForm):

    class Meta:
        model = ExemploModel
        fields = ('nome', 'apelido')
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'size': '50'}),
            'apelido': forms.TextInput(attrs={'class': 'form-control', 'size': '50'}),



        }
        labels = {
            'nome': _('Nome'),
            'apelido': _('Apelido'),
        }

djangocore/apps/base/views.py
# -*- coding: utf-8 -*-

from django.views.generic import TemplateView
from django.shortcuts import render
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import F



from datetime import datetime


class IndexView(TemplateView):
    template_name = 'base/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        data_atual = datetime.now().date()

        context['data_atual'] = data_atual.strftime('%d/%m/%Y')

        return context


def handler404(request):
    response = render(request, '404.html', {})
    response.status_code = 404
    return response


def handler500(request):
    response = render(request, '500.html', {})
    response.status_code = 500
    return response

djangocore/apps/exemplo/views/exemplo.py
# -*- coding: utf-8 -*-

from django.urls import reverse_lazy

from djangocore.apps.base.custom_views import CustomCreateView, CustomListView, CustomUpdateView


from djangocore.apps.exemplo.forms.FormExemplo import ExemploForm
from djangocore.apps.exemplo.models.exemplo import ExemploModel



class ListView(CustomListView):
    template_name = 'exemplo/exemplo_operacao/list.html'
    model = ExemploModel
    context_object_name = 'all_natops'
    success_url = reverse_lazy('exemplo:listaexemplo')
    permission_codename = 'view_naturezaoperacao'

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        context['title_complete'] = 'Exemplo'
        context['add_url'] = reverse_lazy('exemplo:adicionaexemplo')
        return context

class AdicionarView(CustomCreateView):
    #form_class = NaturezaOperacaoForm
    form_class = ExemploForm
    template_name = "exemplo/exemplo_operacao/add.html"
    success_url = reverse_lazy('exemplo:listaexemplo')
    success_message = "Adicionar Exemplo <b>%(cfop)s </b>adicionado com sucesso."
    permission_codename = 'add_naturezaoperacao'

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, cfop=self.object.cfop)

    def get_context_data(self, **kwargs):
        context = super(AdicionarView, self).get_context_data(**kwargs)
        context['title_complete'] = 'ADICIONAR EXEMPLO'
        context['return_url'] = reverse_lazy('exemplo:listaexemplo')
        return context





class EditarView(CustomUpdateView):
    print('Ok')
    form_class = ExemploForm
    model = ExemploModel
   # template_name = "fiscal/natureza_operacao/natureza_operacao_edit.html"
    template_name = "exemplo/exemplo_operacao/edit.html"
    success_url = reverse_lazy('exemplo:listaexemplo')
    success_message = "Natureza da operação <b>%(cfop)s </b>editada com sucesso."
    permission_codename = 'change_naturezaoperacao'

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, cfop=self.object.cfop)

    def get_context_data(self, **kwargs):
        context = super(EditarView,
                        self).get_context_data(**kwargs)
        context['return_url'] = reverse_lazy(
            'exemplo:listaexemplo')
        return context

djangocore/apps/flavio/views/View.py
# -*- coding: utf-8 -*-

from django.urls import reverse_lazy

from djangocore.apps.base.custom_views import CustomCreateView, CustomListView, CustomUpdateView


from djangocore.apps.flavio.forms.Form import *
from djangocore.apps.flavio.models.Model import *

### Carro ###

class ListView(CustomListView):
    template_name = 'flavio/list.html' #'exemplo/exemplo_operacao/list.html'
    model = CarroModel
    context_object_name = 'all_natops'
    success_url = reverse_lazy('flavio:listaflavio')
    permission_codename = 'view_naturezaoperacao'

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        context['title_complete'] = 'Carro'
        context['add_url'] = reverse_lazy('flavio:adicionaflavio')
        return context
#
class AdicionarView(CustomCreateView):
    form_class = CarroForm
    template_name = 'flavio/add.html' #"exemplo/exemplo_operacao/add.html"
    success_url = reverse_lazy('flavio:listaflavio')
    success_message = "Adicionar Exemplo <b>%(cfop)s </b>adicionado com sucesso."
    permission_codename = 'add_naturezaoperacao'

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, cfop=self.object.cfop)

    def get_context_data(self, **kwargs):
        context = super(AdicionarView, self).get_context_data(**kwargs)
        context['title_complete'] = 'ADICIONAR EXEMPLO'
        context['return_url'] = reverse_lazy('flavio:listaflavio')
        return context





class EditarView(CustomUpdateView):
    form_class = CarroForm
    model = CarroModel
   # template_name = "fiscal/natureza_operacao/natureza_operacao_edit.html"
    template_name = 'flavio/edit.html' #"exemplo/exemplo_operacao/edit.html"
    success_url = reverse_lazy('flavio:listaflavio')
    success_message = "Natureza da operação <b>%(cfop)s </b>editada com sucesso."
    permission_codename = 'change_naturezaoperacao'

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, cfop=self.object.cfop)

    def get_context_data(self, **kwargs):
        context = super(EditarView,
                        self).get_context_data(**kwargs)
        context['return_url'] = reverse_lazy(
            'flavio:listaflavio')
        return context




### Pessoa ###

class ListPessoaView(CustomListView):
    template_name = 'flavio/list_pessoa.html'
    model = PessoaModel
    context_object_name = 'all_natops'
    success_url = reverse_lazy('flavio:lista_pessoa')
    permission_codename = 'view_naturezaoperacao'

    def get_context_data(self, **kwargs):
        context = super(ListPessoaView, self).get_context_data(**kwargs)
        context['title_complete'] = 'Pessoa'
        context['add_url'] = reverse_lazy('flavio:adiciona_pessoa')
        return context
#
class AdicionarPessoaView(CustomCreateView):
    form_class = PessoaForm
    template_name = 'flavio/add.html' #"exemplo/exemplo_operacao/add.html"
    success_url = reverse_lazy('flavio:lista_pessoa')
    success_message = "Adicionar Exemplo <b>%(cfop)s </b>adicionado com sucesso."
    permission_codename = 'add_naturezaoperacao'

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, cfop=self.object.cfop)

    def get_context_data(self, **kwargs):
        context = super(AdicionarPessoaView, self).get_context_data(**kwargs)
        context['title_complete'] = 'ADICIONAR EXEMPLO'
        context['return_url'] = reverse_lazy('flavio:lista_pessoa')
        return context





class EditarPessoaView(CustomUpdateView):
    form_class = PessoaForm
    model = PessoaModel
    template_name = 'flavio/edit.html' #"exemplo/exemplo_operacao/edit.html"
    success_url = reverse_lazy('flavio:lista_pessoa')
    success_message = "Natureza da operação <b>%(cfop)s </b>editada com sucesso."
    permission_codename = 'change_naturezaoperacao'

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, cfop=self.object.cfop)

    def get_context_data(self, **kwargs):
        context = super(EditarPessoaView,
                        self).get_context_data(**kwargs)
        context['return_url'] = reverse_lazy(
            'flavio:lista_pessoa')
        return context

djangocore/apps/importador/views/Views.py
from django.urls import reverse_lazy
from siconfipy import get_fiscal, get_budget, br_cods, get_annual_acc
from djangocore.apps.base.custom_views import CustomCreateView, CustomListView, CustomUpdateView

from datetime import timedelta, date, datetime
from djangocore.apps.importador.forms import *
from djangocore.apps.importador.models import *






class ListRGFView(CustomListView):
    template_name = 'RGF/list.html'
    model = RGFModel
    context_object_name = 'all_natops'
    success_url = reverse_lazy('importador:eac')
    permission_codename = 'rgf'

    def get_context_data(self, **kwargs):
        context = super(ListRGFView, self).get_context_data(**kwargs)
        context['title_complete'] = 'RGF'
        return context



class ListEACView(CustomListView):
    template_name = 'EAC/list.html'
    model = EACModel
    context_object_name = 'all_natops'
    success_url = reverse_lazy('importador:eac')
    permission_codename = 'eac'

    def get_context_data(self, **kwargs):
        context = super(ListEACView, self).get_context_data(**kwargs)
        context['title_complete'] = 'EAC'
        return context


class ListRREOView(CustomListView):
    template_name = 'RREO/list.html'
    model = RREOModel
    context_object_name = 'all_natops'
    success_url = reverse_lazy('importador:rreo')
    permission_codename = 'rreo'

    def get_context_data(self, **kwargs):
        context = super(ListRREOView, self).get_context_data(**kwargs)
        context['title_complete'] = 'RREO'
        return context




class ListImportacoesView(CustomListView):
    template_name = 'importador/list.html'
    model = ImportacaoModel
    context_object_name = 'all_natops'
    success_url = reverse_lazy('importador:listimportacoes')
    permission_codename = 'importar_dados'

    def get_context_data(self, **kwargs):
        if self.check_user_permissions(self.request):
            context = super(ListImportacoesView, self).get_context_data(**kwargs)
            context['title_complete'] = 'Importações'
            context['add_url'] = reverse_lazy('importador:adicionaimportacao')
            return context




class AddImportacoesView(CustomListView):
    form_class = ImportacaoForm
    template_name = "importador/add.html"
    success_url = reverse_lazy('importador:listimportacoes')
    success_message = "Importar Dados"
    permission_codename = 'importar_dados'


    def import_rreo(self, ano, bimestre, estado):

        dados = get_budget(year=ano, period=bimestre, cod=estado)
        for index, row in dados.iterrows():
            relatorio = RREOModel.objects.create()
            relatorio.exercicio = row['exercicio']
            relatorio.demonstrativo = row['demonstrativo']
            relatorio.periodo = row['periodo']
            relatorio.periodicidade = row['periodicidade']
            relatorio.instituicao = row['instituicao']
            relatorio.cod_ibge = row['cod_ibge']
            relatorio.uf = row['uf']
            relatorio.anexo = row['populacao']
            relatorio.anexo = row['anexo']
            relatorio.esfera = row['esfera']
            relatorio.rotulo = row['rotulo']
            relatorio.coluna = row['coluna']
            relatorio.cod_conta = row['cod_conta']
            relatorio.conta = row['conta']
            relatorio.valor = row['valor']
            relatorio.importacao = self.object
            relatorio.save()

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            self.object = form.save()

        tipo_relatorio = request.POST['tipo_relatorio']
        ano = request.POST['ano']
        estado = request.POST['estado']
        bimestre = request.POST['bimestre']

#16:51


        if tipo_relatorio == 'RREO':
            estados = {12, 27, 16, 13, 29, 23, 53, 32, 52, 21, 51, 50, 31, 15, 25, 41, 26, 22, 24, 43, 33, 11, 14, 42,
                       35, 28, 17}



            startDate = datetime.datetime.strptime('2015-01-01', '%Y-%m-%d')
            endDate = datetime.datetime.strptime(str(date.today()), '%Y-%m-%d')
            for x in range(startDate.year, endDate.year):
                for y in range(1, 7):
                    print(x, y)
                    for key in estados:
                        self.import_rreo(x, y, key)

            month = date.today().month
            if month > 2:
                for key in estados:
                    self.import_rreo(endDate.year, 1, key)
            if month > 4:
                for key in estados:
                    self.import_rreo(endDate.year, 2, key)
            if month > 6:
                for key in estados:
                    self.import_rreo(endDate.year, 3, key)
            if month > 8:
                for key in estados:
                    self.import_rreo(endDate.year, 4, key)
            if month > 10:
                for key in estados:
                    self.import_rreo(endDate.year, 5, key)
            if month >= 12:
                for key in estados:
                    self.import_rreo(endDate.year, 6, key)

        return super(AddImportacoesView, self).post(request, form, *args, **kwargs)

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, cfop=self.object.cfop)

    def get_context_data(self, **kwargs):
        context = super(AddImportacoesView, self).get_context_data(**kwargs)
        context['title_complete'] = 'Importar Dados'
        context['return_url'] = reverse_lazy('importador:listimportacoes')
        return context




class EditImportacoesView(CustomUpdateView):
    form_class = ImportacaoForm
    model = ImportacaoModel

    template_name = "importador/edit.html"
    success_url = reverse_lazy('importador:listimportacoes')
    success_message = "Importação realizada com sucesso."
    permission_codename = 'importar_dados'

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(cleaned_data, cfop=self.object.cfop)

    def get_context_data(self, **kwargs):
        context = super(EditImportacoesView, self).get_context_data(**kwargs)
        context['return_url'] = reverse_lazy('importador:listimportacoes')
        return context

djangocore/templates/login/detalhe_users.html
{%extends 'base/base.html'%}

{%block title%}Sobre usuário{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid block">
    
    {% include 'base/msg_sucesso.html' %}

    <div class="block-header">
      <h2>USUÁRIO</h2>
    </div>
    <div class="block-content">
      <div class="card">
        <div class="header">
          <h2>
            <a href="{%url 'login:usuariosview'%}"><i class="material-icons">&#xE5C4;</i></a>
            <span><b>Usuário: </b>{{user_match.username}}{% if user_match.is_superuser %} (Admin){% endif %}</span>
          </h2>
          <div class="header-btn">
            {%if not user_match.is_superuser%} 
            <form action="{% url 'login:deletarusuarioview' user_match.id %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="user_id" value="{{user_match.id}}">
              <button class="btn btn-red" type="submit"><i class="material-icons">&#xE872;</i><span> REMOVER</span></button>
            </form>
            {%endif%}
          </div>
        </div>
        <div class="body perfil-user">
            <div class="col-md-3 foto-perfil">  
              {% if user_foto %}
              <img src="/media/{{user_foto}}"/>
              {%else%}
              <img src="/media/imagens/user.png"/>
              {%endif%}
            </div>
            <div class="col-md-8">
              <table class="table">
                <tbody>
                  <tr>
                    <td>Status:</td>
                    <td>{% if user_match.is_superuser %}Administrador{%else%}Usuário{%endif%}</td>
                  </tr>
                  <tr>
                    <td>Nome:</td>
                    <td>{{user_match.first_name}}</td>
                  </tr>
                  <tr>
                    <td>Sobrenome:</td>
                    <td>{{user_match.last_name}}</td>
                  </tr>
                  <tr>
                    <td>Nome de usuário:</td>
                    <td>{{user_match.username}}</td>
                  </tr>
                  <tr>
                    <td>Email:</td>
                    <td>{{user_match.email}}</td>
                  </tr>

                </tbody>
              </table>

            </div>
            <a href="{% url 'login:permissoesusuarioview' user_match.id %}" style="margin:15px;float:right;" class="btn btn-primary">EDITAR PERMISSÕES</a>
        </div>
      </div>
    </div>

    
  </div>
</section>


{%endblock%}

djangocore/templates/login/editar_perfil.html
{%extends 'base/base.html'%}

{%block title%}Editar Perfil{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid block">
    <div class="block-header">
      <h2>PERFIL</h2>
    </div>
      
    {% include 'base/form_error_alert.html' %}

    <div class="block-content">
      <div class="card">
        <div class="header">
          <h2>
            <a href="{% url 'login:perfilview' %}"><i class="material-icons">&#xE5C4;</i></a>
            EDITAR PERFIL
          </h2>
        </div>

        <div class="body">
          <form role="form" action="" method="post" enctype="multipart/form-data" >
           {% csrf_token %}
           
           {% for field in form %}

           <div class="form-group">
            <div class="form-line">
              <label>{{field.label}}</label>
              {{field}}
            </div>
          </div>
          
          {% endfor %}

          <div class="form-group">
            <label>{{minha_empresa_form.m_empresa.label}}</label>
            <div class="input-group">
              <div class="form-line">
                {{minha_empresa_form.m_empresa}}
              </div>
            </div>
          </div>

          <button class="btn btn-success foot-btn" style="margin-right:0px;" type="submit"><i class="material-icons">&#xE3C9;</i><span> ALTERAR</span></button>
        </form>
        
      </div>

    </div>
  </div>
  
</div>
</section>


{%endblock%}

djangocore/templates/login/editar_permissoes_user.html
{%extends 'base/base.html'%}

{%block title%}Permissões do usuário{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid block">
    <div class="block-header">
      <h2>USUÁRIO</h2>
    </div>
    <div>
      <div class="card">
        <div class="header">
          <h2>
            <a href="{%url 'login:usuariodetailview' user.id %}"><i class="material-icons">&#xE5C4;</i></a>
            <span><b>Usuário: </b>{{user.username}}{% if user.is_superuser %} (Admin){% endif %}</span>
          </h2>
        </div>
        <div class="body">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <form action="" method="post">
              {% csrf_token %}
                <select multiple="multiple"  id="id_select_permissoes" name="select_permissoes">
                  {% for default_perm in default_permissions %}
                  <optgroup label='{{default_perm.content_type.app_label|title}}'>
                    <option value='{{default_perm.codename}}' {% if default_perm in user.user_permissions.all or user.is_superuser %}selected{% endif %} {% if user.is_superuser %}disabled='disabled'{% endif %}>
                    {% if 'add' in default_perm.name %}
                    Adicionar {{default_perm.content_type.name}}
                    {% elif 'delete' in default_perm.name %}
                    Deletar {{default_perm.content_type.name}}
                    {% elif 'change' in default_perm.name %}
                    Editar {{default_perm.content_type.name}}
                    {% elif 'views' in default_perm.name %}
                    Visualizar {{default_perm.content_type.name}}
                    {% endif %}
                    </option>
                  </optgroup>
                  {% endfor %}
                  {% for custom_perm in custom_permissions %}
                  <optgroup label='{{custom_perm.content_type.app_label|title}}'>
                    <option value='{{custom_perm.codename}}' {% if custom_perm in user.user_permissions.all or user.is_superuser %}selected{% endif %} {% if user.is_superuser %}disabled='disabled'{% endif %}>
                    {{custom_perm.name}}
                    </option>
                  </optgroup>
                  {% endfor %}
                </select>
                {% if not user.is_superuser %}
                <button class="btn btn-success" style="margin:15px;float:right;" type="submit"><i class="material-icons">&#xE148;</i><span> SALVAR</span></button>
                {% endif %}
              </form>
            </div>
        </div>
      </div>
    </div>

    
  </div>
</section>


{%endblock%}

{% block js %}
    
  {% load static %}
  <!-- Multiselect JS -->
  <script src="{% static 'js/jquery.multi-select.js' %}"></script>
  <link href="{% static 'css/multi-select.css' %}" media="screen" rel="stylesheet" type="text/css">

  {% include 'base/load_jqueryui.html' %}

  {% include 'base/tooltip_js.html' %}

  <script type="text/javascript">
      $('#id_select_permissoes').multiSelect({
      selectableHeader: "<div class='custom-ms-header'>Permissões disponíveis<i class='material-icons' title='Esta é a lista de permissões do usuário disponíveis. Você pode escolhê-los(as) selecionando-os(as) abaixo.'>&#xE887;</i></div>",
      selectionHeader: "<div class='custom-ms-header'>Permissões do usuário {{user.username}}<i class='material-icons' title='Esta é a lista de permissões do usuário disponíveis. Você pode removê-los(as) selecionando-os(as) abaixo.'>&#xE887;</i></div>",
      selectableFooter: "<div class='custom-ms-footer'><a href='#' id='select-all'>selecionar todas</a></div>",
      selectionFooter: "<div class='custom-ms-footer'><a href='#' id='deselect-all'>remover todas</a></div>"});
      $('#select-all').click(function(){
      $('#id_select_permissoes').multiSelect('select_all');
        return false;
      });
      $('#deselect-all').click(function(){
        $('#id_select_permissoes').multiSelect('deselect_all');
        return false;
      });
  </script>
  
{% endblock %}

djangocore/templates/login/lista_users.html
{%extends 'base/base.html'%}

{%block title%}Usuários{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid lista">
    <div class="lista-header">
      <h2>USUÁRIOS</h2>
    </div>
    
    {% include 'base/msg_sucesso.html' %}

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 lista-content">
      <div class="card">
        <form action="" method="post">
          {% csrf_token %}
          <div class="header">
            <h2>
              USUÁRIOS CADASTRADOS
            </h2>
              <div class="header-btn">
                <a href="{% url 'login:registrarview' %}" class="btn btn-success"><i class="material-icons">&#xE7FE;</i><span> CRIAR NOVO</span></a>
                <button class="btn btn-red btn-remove"><i class="material-icons">&#xE872;</i></button>
              </div>
          </div>

          <div class="body">

           {% include 'base/search.html' %}

           <div class="table-responsive">
            <table id="lista-database" class="table table-bordered table-striped lista-table">
              <thead>
                <tr>
                  <th>#ID</th>                   
                  <th>Nome de usuário</th>
                  <th>Nome</th>
                  <th>Sobrenome</th>
                  <th>Status</th>
                  <th>Remover</th>
                </tr>
              </thead>

              <tbody>
               {% if all_users%}
               {% for usr in all_users %}
               <tr class="clickable-row" data-href="{% url 'login:usuariodetailview' usr.id %}">
                <td>{{usr.id}}</td>
                <td>{{usr.username}}</td>
                <td>{{usr.first_name|default_if_none:""}}</td>
                <td>{{usr.last_name|default_if_none:""}}</td>
                <td>{%if usr.is_superuser%}Administrador{%else%}Usuário{%endif%}</td>
                <td class="lista-remove">
                  {%if not usr.is_superuser%}
                  <input type="checkbox" name="{{usr.id}}" id="remover-entrada-{{usr.id}}"/>
                  <label class="remove-entry-label" for="remover-entrada-{{usr.id}}"></label>
                  {%endif%}
                </td>
              </tr>
              {% endfor %}
              {%else%}
              {%endif%}
            </tbody>
          </table>
        </div>

      </div>

    </form>

    {% include 'base/modal.html' %}

  </div>
</div>

</div>
</section>


{%endblock%}

djangocore/templates/login/logo.html
<div class="logo">

    <img src="/static/img/IFG.png"  style="width: 80px; margin-left: 140px" />
    <a href="javascript:void(0);" class="text-logo"><b style="color:#e76d64;"> Guia de Cursos</b></a>
</div>

djangocore/templates/login/trocar_senha_email.html
Mensagem de recuperação de senha. Esta mensagem foi enviada pois ocorreu uma solicitação de troca de senha em seu Django Exemplo.
Abra o link abaixo e defina uma nova senha:
{{protocol}}{{domain}}{% url 'login:trocarsenhaview' uidb64=uid token=token %}

Seu nome de usuário é: {{user}}